name: Indian EPG Grabber
on:
  schedule:
    - cron: '0 */12 * * *' # Grabs data every 12 hours
  workflow_dispatch: # Allows you to grab manually

jobs:
  grab-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch Latest Indian EPG and Channels
        run: |
          # Download Indian EPG (Schedules)
          curl -L "https://raw.githubusercontent.com/iptv-org/epg/refs/heads/master/sites/jiotv.com/jiotv.com.channels.xml" -o public/epg.xml
          # Download Indian Channel List (Logos & IDs)
          curl -L "https://raw.githubusercontent.com/alex8875/m3u/refs/heads/main/jstar.m3u" -o public/channels.m3u

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
